import { Task } from './types/tasks.type';

const tasks: Task[] = [
  {
    id: 1,
    title: 'Update user authentication flow',
    description: 'Implement OAuth2 and add multi-factor authentication support',
    status: 'In Progress',
    statusCode: 1,
    priority: 'High',
    dueDate: '2024-01-15',
    assignedTo: 'Emma Thompson',
    tags: ['Security', 'Authentication'],
  },
  {
    id: 2,
    title: 'Optimize database queries',
    description: 'Review and improve SQL queries for better performance',
    status: 'Pending',
    statusCode: 2,
    priority: 'Medium',
    dueDate: '2024-01-20',
    assignedTo: 'Michael Chen',
    tags: ['Database', 'Performance'],
  },
  {
    id: 3,
    title: 'Fix mobile responsive layout',
    description: 'Address UI issues on smaller screen devices',
    status: 'To Do',
    statusCode: 0,
    priority: 'High',
    dueDate: '2024-01-10',
    assignedTo: 'Sarah Wilson',
    tags: ['UI/UX', 'Mobile'],
  },
  {
    id: 4,
    title: 'Implement error logging system',
    description: 'Set up centralized error tracking and monitoring',
    status: 'In Progress',
    statusCode: 1,
    priority: 'Medium',
    dueDate: '2024-01-25',
    assignedTo: 'David Miller',
    tags: ['DevOps', 'Monitoring'],
  },
  {
    id: 5,
    title: 'Create user onboarding flow',
    description: 'Design and implement new user welcome experience',
    status: 'To Do',
    statusCode: 0,
    priority: 'Low',
    dueDate: '2024-02-01',
    assignedTo: 'Lisa Anderson',
    tags: ['UX', 'Frontend'],
  },
  {
    id: 6,
    title: 'Update API documentation',
    description: 'Review and update Swagger documentation for v2 endpoints',
    status: 'Completed',
    statusCode: 3,
    priority: 'Low',
    dueDate: '2024-01-08',
    assignedTo: 'James Wright',
    tags: ['Documentation', 'API'],
  },
  {
    id: 7,
    title: 'Implement payment gateway',
    description: 'Integrate Stripe payment processing system',
    status: 'In Progress',
    statusCode: 1,
    priority: 'High',
    dueDate: '2024-01-30',
    assignedTo: 'Robert Kim',
    tags: ['Payment', 'Integration'],
  },
  {
    id: 8,
    title: 'Setup automated testing',
    description: 'Configure Jest and implement unit tests',
    status: 'Pending',
    statusCode: 2,
    priority: 'Medium',
    dueDate: '2024-02-05',
    assignedTo: 'Anna Martinez',
    tags: ['Testing', 'QA'],
  },
  {
    id: 9,
    title: 'Optimize image loading',
    description: 'Implement lazy loading for images and compress assets',
    status: 'To Do',
    statusCode: 0,
    priority: 'Low',
    dueDate: '2024-01-18',
    assignedTo: 'Chris Johnson',
    tags: ['Performance', 'Frontend'],
  },
  {
    id: 10,
    title: 'Update dependencies',
    description: 'Upgrade all npm packages to latest stable versions',
    status: 'In Progress',
    statusCode: 1,
    priority: 'Medium',
    dueDate: '2024-01-12',
    assignedTo: 'Tom Wilson',
    tags: ['Maintenance', 'Dependencies'],
  },
  {
    id: 11,
    title: 'Implement dark mode',
    description: 'Add theme switching functionality and dark mode styles',
    status: 'To Do',
    statusCode: 0,
    priority: 'Low',
    dueDate: '2024-02-15',
    assignedTo: 'Sophie Brown',
    tags: ['UI/UX', 'Frontend'],
  },
  {
    id: 12,
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions for automated deployment',
    status: 'Pending',
    statusCode: 2,
    priority: 'High',
    dueDate: '2024-01-22',
    assignedTo: 'Alex Turner',
    tags: ['DevOps', 'Automation'],
  },
];
export default tasks;
